apiVersion: v1
kind: Service
metadata:
  labels:
    app: db2luw-destination
  name: db2luw-destination
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "50000"
    port: 50000
    targetPort: 50000
  selector:
    app: db2luw-destination
status:
  loadBalancer: {}
