apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql5-destination
  name: mysql5-destination
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mysql5-destination
status:
  loadBalancer: {}
