apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql5-destination
  namespace: {{ .Release.Namespace }}
  annotations:
    security.alpha.kubernetes.io/sysctls: fs.aio-max-nr=1048576
  labels:
    app: mysql5-destination
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql5-destination
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql5-destination
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: example
        - name: LANG
          value: C.UTF-8
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql5-destination
        args: ["--default-authentication-plugin=mysql_native_password", "--local-infile", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--secure-file-priv=/var/lib/mysql-files/", "--sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "256Mi"
            ephemeral-storage: "512Mi"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - find /proc -mindepth 2 -maxdepth 2 -name exe -exec ls -lh {} \; 2>/dev/null | grep mysql
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - find /proc -mindepth 2 -maxdepth 2 -name exe -exec ls -lh {} \; 2>/dev/null | grep mysql
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
      serviceAccountName: ""
