apiVersion: v1
kind: Service
metadata:
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
{{- if  ((.Values.tonicai).web_server).annotations }}
  annotations:
    {{- toYaml .Values.tonicai.web_server.annotations | nindent 4 }}
{{- end }}

  labels:
    app: tonic-web-server
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: 443
  type: ClusterIP
  selector:
    app: tonic-web-server
status:
  loadBalancer: {}
