apiVersion: v1
kind: Service
metadata:
  name: tonic-integration-test-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: tonic-integration-test-api
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: 3600
  type: ClusterIP
  selector:
    app: tonic-integration-test-api
status:
  loadBalancer: {}
