---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "tonic-web-server"
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: "{{.Values.prappDetails.name}}.dev.tonic.ai"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "tonic-web-server"
                port:
                  name: "https"
