apiVersion: v1
kind: Service
metadata:
  name: tonic-integration-test-api
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:939426802623:certificate/3c21c3b3-ceb0-4f9b-b803-5bcd5baf5c17"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0213261cea53c795d"

  labels:
    app: tonic-integration-test-api
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: 3600
  type: LoadBalancer
  selector:
    app: tonic-integration-test-api
status:
  loadBalancer: {}
